export const users = [
  {
    id: "SD1901",
    fullName: "An Nguyen Thuy",
    username: "annt",
    joinedDate: "20/06/2019",
    type: "Staff",
  },
  {
    id: "SD1234",
    fullName: "An Tran Van",
    username: "antv",
    joinedDate: "09/04/2019",
    type: "Staff",
  },
  {
    id: "SD0971",
    fullName: "Binh Nguyen Van",
    username: "binhv1",
    joinedDate: "08/03/2018",
    type: "Admin",
  },
  {
    id: "SD0973",
    fullName: "Binh Nguyen Van",
    username: "binhv2",
    joinedDate: "08/03/2018",
    type: "Staff",
  },
  {
    id: "SD0974",
    fullName: "Binh Nguyen Van",
    username: "binhv3",
    joinedDate: "08/03/2018",
    type: "Staff",
  },
  {
    id: "SD0976",
    fullName: "Binh Nguyen Van",
    username: "binhv4",
    joinedDate: "08/03/2018",
    type: "Staff",
  },
  {
    id: "SD0977",
    fullName: "Binh Nguyen Van",
    username: "binhv5",
    joinedDate: "08/03/2018",
    type: "Staff",
  },
  {
    id: "SD0978",
    fullName: "Binh Nguyen Van",
    username: "binhv6",
    joinedDate: "08/03/2018",
    type: "Staff",
  },
  {
    id: "SD0979",
    fullName: "Binh Nguyen Van",
    username: "binhv7",
    joinedDate: "08/03/2018",
    type: "Staff",
  },
  {
    id: "SD0980",
    fullName: "Binh Nguyen Van",
    username: "binhv8",
    joinedDate: "08/03/2018",
    type: "Staff",
  },
  {
    id: "SD0981",
    fullName: "Binh Nguyen Van",
    username: "binhv9",
    joinedDate: "08/03/2018",
    type: "Staff",
  },
  {
    id: "SD0982",
    fullName: "Binh Nguyen Van",
    username: "binhv10",
    joinedDate: "08/03/2018",
    type: "Staff",
  },
  {
    id: "SD0983",
    fullName: "Binh Nguyen Van",
    username: "binhv11",
    joinedDate: "08/03/2018",
    type: "Staff",
  },
  {
    id: "SD0984",
    fullName: "Binh Nguyen Van",
    username: "binhv12",
    joinedDate: "08/03/2018",
    type: "Staff",
  },
  {
    id: "SD0985",
    fullName: "Binh Nguyen Van",
    username: "binhv13",
    joinedDate: "08/03/2018",
    type: "Staff",
  },
  {
    id: "SD0986",
    fullName: "Binh Nguyen Van",
    username: "binhv14",
    joinedDate: "08/03/2018",
    type: "Staff",
  },
  {
    id: "SD0987",
    fullName: "Binh Nguyen Van",
    username: "binhv15",
    joinedDate: "08/03/2018",
    type: "Staff",
  },
];
