#!/usr/bin/env bash

# Very specific fix: Force WSL nvm to run, not Windows nvm

set -e

if uname -a | grep -qiE "Linux|WSL";
then
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    command -v nvm use default >/dev/null
fi

# Actual hook

npm run lint && npm run format:write
